name: offline_uncensored_ai
description: Offline Uncensored AI for Poco F5.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  llamadart: ^0.6.5

flutter:
  uses-material-design: true
  assets:
    - assets/models/
